# This is a basic workflow to help you get started with Actions

name: Build docker image

on:
  push:
    tags:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Get image version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}"
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: docker buildx build --push \
          --tag jeromebehe/jenkins-rpi:latest \
          --tag jeromebehe/jenkins-rpi:$RELEASE_VERSION \
          --platform linux/arm . 
  
  
